name: 'get-secrets-vault'
description: 'Export all key-value pairs from Vault secret path(s) to environment'
inputs:
  vault_addr:
    required: true
    description: 'Vault address'
  token:
    required: true
    description: 'Vault token'
  secret_paths:
    required: true
    description: 'Comma-separated list of Vault secret paths (KV v2)'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if ! command -v vault &> /dev/null; then
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install vault -y
        fi
        export VAULT_ADDR="${{ inputs.vault_addr }}"
        export VAULT_TOKEN="${{ inputs.token }}"
        MOUNT="kv"
        IFS=',' read -ra PATHS <<< "${{ inputs.secret_paths }}"
        for path in "${PATHS[@]}"; do
          secret_json=$(vault kv get -mount="$MOUNT" -format=json "$path" 2>/dev/null || echo "")
          if [ -n "$secret_json" ] && [ "$(echo "$secret_json" | jq '.data.data != null')" = "true" ]; then
            echo "$secret_json" | jq -r '.data.data | to_entries[] | "VAULT_\(.key | toupper)=\(.value)"' >> $GITHUB_ENV
          else
            echo "[get-secrets-vault] Warning: No data or cannot access $path" >&2
          fi
        done